language: node_js

node_js:
  - 12

addons:
  apt:
    packages:
      # cypress dep
      - libgconf-2-4

cache:
  yarn: true
  directories:
    - ~/.npm
    - ~/.cache
    - node_modules

install:
  - yarn --frozen-lockfile

script:
  - yarn lint
  - yarn build
  - yarn test:ci
